name: CI/CD Pipeline

on:
  push:
    branches: [Azure]
  pull_request:
    branches: [Azure]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mypostgresapi-publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: mypostgresapi-publish
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
