name: .NET 9 Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ASPNETCORE_ENVIRONMENT: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET 9.0 Preview SDK
        run: |
            curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.100-preview --install-dir $HOME/dotnet
            echo "$HOME/dotnet" >> $GITHUB_PATH
            echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
    
      - name: Verify .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Generate .env file with secrets
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "TEST_DB_CONNECTION=Host=localhost;Port=5432;Username=postgres;Password=${{ secrets.DB_PASSWORD }};Database=postgres;Search Path=test_schema" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

      - name: Run tests
        run: |
          export $(grep -v '^#' .env | xargs)
          dotnet build
          dotnet test --no-build --verbosity normal
